Started by user [8mha:////4E20/w1GckiA/nocQ1f5cF/jB0ZhiDWNy4jAx3sKJkWvAAAAlx+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgZu/dLi1CL9xJTczDwAZ3pnlMAAAAA=[0miGot
Rebuilds build #[8mha:////4BvYvDKhnlky2oWzQVhzp5CJFpm95ukRAq4Jm7dxSJmiAAAAph+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAymEgYl/az8JP3M9PwS3ZTUgpz8SjA/saAgHso1MgQA5ZpKTdcAAAA=[0m21
Running as SYSTEM
Building in workspace /var/lib/jenkins/workspace/igot-deploy/app_deploy
[app_deploy] $ /bin/bash /tmp/jenkins6763098982516959505.sh
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/vars/main.yml, line 6, column 1, found[0m
[1;35ma duplicate dict key (service_sb_telemetry_port). Using last defined value[0m
[1;35monly.[0m
[1;35m[0m
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/roles/deploy-lex-core-[0m
[1;35mservice/defaults/main.yml, line 3, column 1, found a duplicate dict key[0m
[1;35m(sunbird_time_zone). Using last defined value only.[0m
[1;35m[0m
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/roles/deploy-lex-core-[0m
[1;35mservice/defaults/main.yml, line 3, column 1, found a duplicate dict key[0m
[1;35m(nginx_per_ip_connection_limit). Using last defined value only.[0m
[1;35m[0m
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/roles/deploy-lex-core-[0m
[1;35mservice/defaults/main.yml, line 3, column 1, found a duplicate dict key[0m
[1;35m(sunbird_portal_player_cdn_enabled). Using last defined value only.[0m
[1;35m[0m
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/roles/deploy-lex-core-[0m
[1;35mservice/defaults/main.yml, line 3, column 1, found a duplicate dict key[0m
[1;35m(search_liveness_readiness). Using last defined value only.[0m
[1;35m[0m
[1;35m [WARNING]: While constructing a mapping from[0m
[1;35m/home/ubuntu/test/ansible_workspace_dir/roles/deploy-lex-core-[0m
[1;35mservice/defaults/main.yml, line 3, column 1, found a duplicate dict key[0m
[1;35m(taxonomy_liveness_readiness). Using last defined value only.[0m
[1;35m[0m

PLAY [dev] *********************************************************************

TASK [Gathering Facts] *********************************************************
[0;32mok: [localhost][0m

TASK [deploy-content-validation-service : template values.yaml file] ***********
[0;32mok: [localhost][0m

TASK [deploy-content-validation-service : template configmap file] *************
[0;33mchanged: [localhost][0m

TASK [deploy-content-validation-service : create env configmap] ****************
[0;33mchanged: [localhost][0m

TASK [deploy-content-validation-service : remove env configmap file] ***********
[0;33mchanged: [localhost][0m

TASK [deploy-content-validation-service : helm upgrade] ************************
[0;31mfatal: [localhost]: FAILED! => {[0m
[0;31m    "changed": true, [0m
[0;31m    "cmd": "helm upgrade --install --atomic --timeout 10m content-validation-service ../kubernetes-deploy/content-validation-service -n dev", [0m
[0;31m    "delta": "0:00:01.126659", [0m
[0;31m    "end": "2020-12-18 11:20:23.640877", [0m
[0;31m    "rc": 1, [0m
[0;31m    "start": "2020-12-18 11:20:22.514218"[0m
[0;31m}[0m
[0;31m[0m
[0;31mSTDOUT:[0m
[0;31m[0m
[0;31mRelease "content-validation-service" does not exist. Installing it now.[0m
[0;31m[0m
[0;31m[0m
[0;31mSTDERR:[0m
[0;31m[0m
[0;31mError: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: kind: Service, namespace: dev, name: content-validation[0m
[0;31m[0m
[0;31m[0m
[0;31mMSG:[0m
[0;31m[0m
[0;31mnon-zero return code[0m
[0;31m[0m
	to retry, use: --limit @/home/ubuntu/test/ansible_workspace_dir/main.retry

PLAY RECAP *********************************************************************
[0;31mlocalhost[0m                  : [0;32mok=5   [0m [0;33mchanged=3   [0m unreachable=0    [0;31mfailed=1   [0m

Build step 'Execute shell' marked build as failure
Finished: FAILURE
